version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager --caliper-fabric-gateway-usegateway --caliper-flow-only-test --caliper-fabric-gateway-discovery --caliper-fabric-gateway-localhost=false
        environment:
        - CALIPER_BIND_SUT=fabric:2.2
        - CALIPER_BENCHCONFIG=benchmarks/samples/fabric/fabcar/config.yaml
        - CALIPER_NETWORKCONFIG=networks/fabric/test-network.yaml
        volumes:
        - ./caliper-benchmarks:/hyperledger/caliper/workspace